### ISSUE TITLE
Stop containers on shutdown

### ISSUE THREAD

**Issue by betatim** [everware/jupyterhub#4]
Need to keep track of all containers we start so we can shut them down properly when stopping the hub.

**Comment by betatim** [comment]
Having though about this a bit I think we should remove the container (not the image) when a user logs out. It means there is no state. If I login with a user name/repo combo, I always get the same thing. No matter whether I previously logged in with this combo or not.

Pros:
- no zombie containers, housekeeping becomes easier
- stateless
- supports http://everware.com/magic-word/url-encoded-repo-url-here to directly launch a new environment

Cons:
- you can not start looking at a repo A, modify it, logout, look at a different repo B, and then return to repo A and still see your changes.
- recreating the container from the image might take longer than just reconnecting the running container

**Comment by OmeGak** [comment]
If we added OAuth we could make Everware to save your modifications on GitHub. If the user has write rights on the repo, we would simply create a new commit and push it. Otherwise, we fork the repo for the user and commit there.

**Comment by ibab** [comment]
I think one problem with shutdown on logout is that we would have to keep a lot of containers running all the time. (One for every user that hasn't logged out)
So maybe there should still be an inactivity period (of let's say a few hours) after which the container is stopped.

**Comment by betatim** [comment]
Good point. In `tmpnb` there is a inactivity culler, if it isn't already in
`jupyterhub` we should add that.

Removing a container on logout makes the problem a little less worse. Right
now we are accumulating containers like crazy :)

Auto pushing is an interesting idea, though it makes me a little nervous
(pushing to master :danger: ) We could create a new branch though (with
some clever naming scheme?) and push to that on github. Maybe add it as an
option/button that is shown on logout?

**Comment by betatim** [comment]
This is also done I think. If participants disagree, reopen it in `everware/everware`
